### ISSUE TITLE
Receiving Error 424 when attempting to play

### ISSUE THREAD

**Issue by ClaireisBored** [DanMossa/paliaOnMac-release#2]
Hey there, thanks for making and publishing this! I've been able to install the game and login, however, whenever I hit play I'm met with error 424, unable to connect. I know it is not an issue with my actual internet connection. Has a fix been discovered for this, am I doing something wrong, etc?
<img width="479" alt="Screenshot 2023-09-13 at 9 06 43 pm" src="https://github.com/DanMossa/paliaOnMac-release/assets/144974034/006a8530-d37c-422f-8e24-c503135ef21f">

**Comment by Allexz1** [comment]
I can confirm, having the same issue.
When i click update in the launcher it just instantly exits the application.
Also when ingame menu instead of displaying the actual version in the bottom left corner it says unknown version.

**Comment by DanMossa** [comment]
Fixed in 0.2.3
https://github.com/DanMossa/paliaOnMac-release/releases/tag/0.2.3

**Comment by ClaireisBored** [comment]
Hey there! Thanks so much for the super timely response downloaded 0.2.3 and still having the same issue unfortunately. Went back to 0.1.5 as suggested and still had the same thing, error 424, unable to connect. 
<img width="479" alt="Screenshot 2023-09-13 at 9 06 43 pm" src="https://github.com/DanMossa/paliaOnMac-release/assets/144974034/021bbbf1-dffc-4eb3-ab78-6744341609a1">

**Comment by DanMossa** [comment]
@ClaireisBored Oh! Go ahead and click update on the launcher and then try again!

**Comment by Allexz1** [comment]
I can confirm.

Manually hitting the update button made it all work again! Thanks!
